# Generated by Django 3.2.8 on 2023-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField()),
                ('is_finish', models.IntegerField(default=0)),
                ('finish_time', models.DateTimeField(blank=True)),
                ('body', models.TextField()),
                ('list_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('all_finish', models.IntegerField(default=0)),
                ('create_datetime', models.DateTimeField()),
                ('can_change', models.IntegerField(default=0)),
                ('finish_rate', models.CharField(default='0/0', max_length=100)),
            ],
        ),
    ]
