# Generated by Django 4.2.4 on 2023-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='all_finish',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='can_change',
        ),
        migrations.AddField(
            model_name='todolist',
            name='close_datetime',
            field=models.DateField(auto_now=True, help_text='关闭时间 根据is_close字段来判断是否关闭'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='expect_finish_date',
            field=models.DateTimeField(auto_now=True, help_text='预计完成时间'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_close',
            field=models.SmallIntegerField(default=0, help_text='0: 未关闭 1: 关闭'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='tag',
            field=models.IntegerField(default=0, help_text='0:周目标 1:月目标 2:短期目标 3:长期目标'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='未填写标题', max_length=200),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
    ]
