# Generated by Django 4.2.4 on 2023-09-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_id_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
