# Generated by Django 3.2.8 on 2023-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('username', models.CharField(help_text='用户名', max_length=100)),
                ('password', models.CharField(help_text='密码', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=254)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
