# Generated by Django 3.2.8 on 2023-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='post_id',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
