# Generated by Django 3.2.8 on 2021-12-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cate',
            new_name='name',
        ),
    ]
