# Generated by Django 3.2.8 on 2022-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220120_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='subhead',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
