# Generated by Django 3.2.8 on 2022-07-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceCate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='blog.sentencecate')),
            ],
        ),
    ]
