# Generated by Django 3.2.8 on 2022-10-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_sentence_sentencecate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='post_img',
        ),
        migrations.AlterModelTable(
            name='sentence',
            table='sentence',
        ),
        migrations.AlterModelTable(
            name='sentencecate',
            table='sentence_cate',
        ),
    ]
